name:                BruSKI
version:             0.1.0.0
github:              "bruski.nicklasbotö.se"
license:             GPL
author:              "Nicklas Botö"
maintainer:          "nicklas.boto@gmail.com"
copyright:           "BruSKI  Copyright (C) 2020  Nicklas Botö"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at learnbruski.nicklasbotö.se

dependencies:
- base >= 4.7 && < 5
- parsec
- containers
- mtl
- with-utf8
- turtle

library:
  source-dirs: src

executables:
  bruc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BruSKI
    - turtle

tests:
  BruSKI-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BruSKI
